name: chrome
description: "set up Chrome environment"
outputs:
  chrome-path:
    description: "Path to the chrome executable"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
runs:
  using: "composite"
  steps:
    - name: install chrome
      uses: browser-actions/setup-chrome@v2
      id: setup-chrome
      with:
        #install-dependencies: true
        chrome-version: stable
        #install-chromedriver: true

    - name: init chrome Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        chrome --version
        chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 about:blank &
          CHROME_PID=$!
          waitfor --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
          if [ $? -ne 0 ]; then
            kill $CHROME_PID
            exit 1
          fi
          kill $CHROME_PID

    - name: init chrome Windows
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: |
        $chromePath = "${env:ProgramFiles}\Google\Chrome\Application\chrome.exe"
        (Get-Item "$chromePath").VersionInfo.ProductVersion
        & "$chromePath" --headless --disable-gpu --remote-debugging-port=9222 about:blank
        $profilePath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default"
        if (waitfor --initial=5s --interval=1s --total=30s $profilePath) {
        } else {
          exit 1
        }

    - name: init chrome macOS
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 about:blank &
        CHROME_PID=$!
        waitfor --initial=5s --interval=1s --total=30s "$HOME/Library/Application Support/Google/Chrome/Default"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
          exit 1
        fi
        kill $CHROME_PID
