name: chrome
description: "set up Chrome environment"
outputs:
  chrome-path:
    description: "Path to the chrome executable"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
  chrome-user-data-dir:
    description: "Path to the chrome user data directory"
    value: ${{ steps.resolve-user-data.outputs.chrome-user-data-dir }}

runs:
  using: "composite"
  steps:
    - name: install chrome for testing #on Linux and Windows
      shell: bash
      id: setup-chrome
      run: |
        go install github.com/cloudengio/citools/chrome-for-testing/cmd/chrome-for-testing@chrome-for-testing
        chrome-for-testing --channel=stable install
      #if: ${{ runner.os != 'macOS' && runner.environment != 'self-hosted' }}
      #uses: browser-actions/setup-chrome@v2.1.0
      #id: setup-chrome
      #with:
      #  install-dependencies: true
      #  chrome-version: stable

    - name: resolve chrome user data dir
      id: user-data-dir
      shell: bash
      env:
        USERDATA_DIR: '{"Linux": "$HOME/.config/google-chrome-for-testing", "Windows": "$RUNNER_TEMP\\chrome-user-data", "macOS": "$HOME/Library/Application Support/Google/Chrome for Testing"}'
      run: |
        echo "chrome-user-data-dir=${{ fromJSON(env.USERDATA_DIR)[runner.os] }}" >> "$GITHUB_OUTPUT"

    - name: init chrome Linux
      shell: bash
      id: init-linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
        USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
        "$CHROME_PATH" --version
        "$CHROME_PATH" --headless=new --disable-gpu --no-sandbox --remote-debugging-port=9222 --user-data-dir="$USERDATA_DIR" about:blank &
        CHROME_PID=$!
        waitforfiles --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
            exit 1
          fi
        kill $CHROME_PID

        # this should already exist.
        waitforfiles --interval=0 --total=0 "$USERDATA_DIR/Default"
        echo "user-data-dir=$USERDATA_DIR" >> "$GITHUB_OUTPUT"

    - name: init chrome Windows
      shell: pwsh
      id: init-windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        $chromePath = "${{ steps.setup-chrome.outputs.chrome-path }}"
        $userDataDir = "${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"

        & "$chromePath" --version

        # Set sandbox permissions
        $chromeDir = Split-Path -Parent $chromePath
        icacls "$chromeDir" /grant 'ALL APPLICATION PACKAGES:(OI)(CI)(RX)' /grant 'ALL RESTRICTED APPLICATION PACKAGES:(OI)(CI)(RX)' /T /C | Out-Null
        if ($LASTEXITCODE -ne 0) {
          throw "icacls failed to set sandbox permissions on $chromeDir"
        }

        $profilePath = Join-Path $userDataDir "Default"

        $flags = @(
          "--headless=new",
          "--disable-gpu",
          "--no-sandbox",
          "--remote-debugging-port=9222",
          "--user-data-dir=$userDataDir",
          "about:blank"
        )

        $process = Start-Process -FilePath "$chromePath" -ArgumentList $flags -PassThru

        $goBinPath = (go env GOBIN)
        if (-not $goBinPath) {
          $goBinPath = (go env GOPATH) + "\bin"
        }

        & "$goBinPath\waitforfiles.exe" --initial=5s --interval=1s --total=30s $profilePath
        Stop-Process -Id $process.Id -Force

    - name: init chrome macOS
      shell: bash
      id: init-macos
      if: ${{ runner.os == 'macOS' }}
      run: |
        #CHROME_PATH="/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"

        "$CHROME_PATH" --version

        USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"

        PROFILE_DIR="$USERDATA_DIR/Default"

        mkdir -p "$PROFILE_DIR"

        "$CHROME_PATH" \
            --headless=new \
            --no-sandbox \
            --disable-gpu \
            --no-first-run \
            --no-default-browser-check \
            --user-data-dir="$USERDATA_DIR" \
            about:blank &

        CHROME_PID=$!

        waitforfiles --initial=2s --interval=1s --total=30s "$PROFILE_DIR"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
          exit 1
        fi
        kill $CHROME_PID
