name: chrome
description: "set up Chrome environment"
outputs:
  chrome-path:
    description: "Path to the chrome executable"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
  chrome-user-data-dir:
    description: "Path to the chrome user data directory"
    value: ${{ steps.chrome-user-data-dir.outputs.chrome-user-data-dir }}

runs:
  using: "composite"
  steps:
    - name: install chrome
      uses: browser-actions/setup-chrome@v2
      id: setup-chrome
      with:
        chrome-version: stable

    - name: init chrome Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
        "$CHROME_PATH" --version
        "$CHROME_PATH" --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 about:blank &
        CHROME_PID=$!
        waitforfiles --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
            exit 1
          fi
          kill $CHROME_PID

          USERDATA_DIR="/home/runner/.config/google-chrome-for-testing"

    - name: init chrome Windows
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: |
        $originalChromePath = "${{ steps.setup-chrome.outputs.chrome-path }}"
        & "$originalChromePath" --version

        $originalChromeDir = Split-Path -Parent $originalChromePath
        $tempChromeBase = Join-Path $env:RUNNER_TEMP "chrome-launch"
        if (Test-Path $tempChromeBase) {
          Remove-Item -Path $tempChromeBase -Recurse -Force
        }
        New-Item -Path $tempChromeBase -ItemType Directory | Out-Null
        Get-ChildItem -Path $originalChromeDir -Force | Copy-Item -Destination $tempChromeBase -Recurse -Force
        $chromePath = Join-Path $tempChromeBase "chrome.exe"

        $flags = @(
          "--headless",
          "--disable-gpu",
          "--no-sandbox",
          "--remote-debugging-port=9222",
          "--disable-features=Translate,MediaRouter,OptimizationHints,Prerender2",
          "--disable-background-networking",
          "--disable-sync",
          "--disable-default-apps",
          "--user-data-dir=$env:LOCALAPPDATA\Google\Chrome\User Data",
          "about:blank"
        )

        $process = Start-Process -FilePath "$chromePath" -ArgumentList $flags -PassThru
        try {
          $profilePath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default"

          $goBinPath = (go env GOBIN)
          if (-not $goBinPath) {
            $goBinPath = (go env GOPATH) + "\bin"
          }

          & "$goBinPath\waitforfiles.exe" --initial=5s --interval=1s --total=30s $profilePath
          if ($LASTEXITCODE -ne 0) {
            throw "waitforfiles.exe timed out waiting for $profilePath"
          }
        } finally {
          if ($process -and -not $process.HasExited) {
            Stop-Process -Id $process.Id -Force
          }
        }

    - name: init chrome macOS
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
        "$CHROME_PATH" --version
        export HOME=/Users/runner
        USERDATA_DIR="$HOME/Library/Application Support/Google/Chrome for Testing"
        PROFILE_DIR="$USERDATA_DIR/Default"
        echo $USERDATA_DIR

        mkdir -p "$PROFILE_DIR"

        "$CHROME_PATH" --headless=new --disable-gpu --no-sandbox --remote-debugging-port=9222 --disable-dev-shm-usage --user-data-dir="$USERDATA_DIR" about:blank &
        CHROME_PID=$!

        waitforfiles --initial=2s --interval=1s --total=30s "$PROFILE_DIR"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
          exit 1
        fi
        kill $CHROME_PID

    - name: chrome user data dir outputs
      shell: bash
      id: chrome-user-data-dir
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          USERDATA_DIR="/Users/runner/Library/Application Support/Google/Chrome for Testing"
          echo "chrome-user-data-dir=$USERDATA_DIR" >> $GITHUB_OUTPUT
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          USERDATA_DIR="/home/runner/.config/google-chrome-for-testing"
          echo "chrome-user-data-dir=$USERDATA_DIR" >> $GITHUB_OUTPUT
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "chrome-user-data-dir=$env:LOCALAPPDATA\Google\Chrome\User Data" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        fi
