name: chrome
description: "set up Chrome environment"
outputs:
  chrome-path:
    description: "Path to the chrome executable"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
  chrome-user-data-dir:
    description: "Path to the chrome user data directory"
    value: ${{ steps.setup-chrome.outputs.chrome-user-data-dir }}

runs:
  using: "composite"
  steps:
    - name: install chrome for testing
      shell: bash
      id: setup-chrome
      run: |
        go install cloudeng.io/citools/chrome-for-testing@latest
        chrome-for-testing install --channel=stable --application=chrome --initialize
