name: chrome
description: "set up Chrome environment"
runs:
  using: "composite"
  steps:
    - name: install chrome
      uses: browser-actions/setup-chrome@v2
      id: setup-chrome
      with:
        install-dependencies: true

    - name: init chrome Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        chrome --version
        chrome --headless --disable-gpu --no-sandbox about:blank &
          CHROME_PID=$!
          NSS_DB_PATH="$HOME/.pki/nssdb"
          # Wait up to 30s for Chrome to create the NSS DB
          for i in {1..30}; do
            if [ -d "$NSS_DB_PATH" ]; then
              echo "✅ NSS DB found"
              break
            fi
          echo "⏳ Waiting for NSS DB to be created... ($i)"
          sleep 1
          done

          kill $CHROME_PID

          if [ ! -d "$NSS_DB_PATH" ]; then
            echo "❌ NSS DB was not created after 30s"
            exit 1
          fi

    - name: init chrome Windows
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: |
        & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
        & "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless --disable-gpu about:blank
        Start-Sleep -Seconds 5

    - name: init chrome macOS
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --no-sandbox about:blank &

        CHROME_PID=$!

        PROFILE_PATH="$HOME/Library/Application Support/Google/Chrome/Default"

        # Wait up to 30s for Chrome to create the default profile.
        for i in {1..30}; do
          if [ -d "$PROFILE_PATH" ]; then
            echo "✅ Default profile created"
            break
          fi
          echo "⏳ Waiting for Default profile to be created... ($i)"
          sleep 1
          ls -l "$(dirname "$PROFILE_PATH")" || true
        done

        kill $CHROME_PID

        if [ ! -d "$PROFILE_PATH" ]; then
          echo "❌ Default profile was not created after 30s"
          exit 1
        fi
