name: chrome
description: "set up Chrome environment"
outputs:
  chrome-path:
    description: "Path to the chrome executable"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
runs:
  using: "composite"
  steps:
    - name: install chrome
      uses: browser-actions/setup-chrome@v2
      id: setup-chrome
      with:
        chrome-version: stable

    - name: init chrome Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        chrome --version
        chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 about:blank &
          CHROME_PID=$!
          waitforfiles --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
          if [ $? -ne 0 ]; then
            kill $CHROME_PID
            exit 1
          fi
          kill $CHROME_PID

    - name: init chrome Windows
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: |
        $chromePath = "${{ steps.setup-chrome.outputs.chrome-path }}"
        (Get-Item "$chromePath").VersionInfo.ProductVersion

        & "$chromePath" --headless --disable-gpu --remote-debugging-port=9222 about:blank
        $profilePath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default"

        $goBinPath = (go env GOBIN)
        if (-not $goBinPath) {
          $goBinPath = (go env GOPATH) + "\bin"
        }
        & "$goBinPath\waitfor.exe" --initial=5s --interval=1s --total=30s $profilePath

    - name: init chrome macOS
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
        "$CHROME_PATH" --version
        export HOME=/Users/runner
        USERDATA_DIR="$HOME/Library/Application Support/Google/Chrome for Testing"
        PROFILE_DIR="$USERDATA_DIR/Default"

        mkdir -p "$PROFILE_DIR"

        "$CHROME_PATH" --headless=new --disable-gpu --no-sandbox --remote-debugging-port=9222 --disable-dev-shm-usage --user-data-dir="$USERDATA_DIR" about:blank &
        CHROME_PID=$!

        waitforfiles --initial=5s --interval=1s --total=30s "$PROFILE_DIR"
        if [ $? -ne 0 ]; then
          kill $CHROME_PID
          exit 1
        fi
        kill $CHROME_PID
