name: apple keychain support
description: create a file based keychain, note the search path and default keychains are modified to use the created keychain
inputs:
  keychain-name:
    description: "Name of the keychain to create"
    required: false
    default: "keychain-ci-testing.keychain-db"
  keychain-password:
    description: "Password for the keychain, a random one will be generated if not provided"
    required: false
    default: ""
  certificate-p12-base64:
    description: "Base64 encoded P12 certificate"
    required: false
outputs:
  keychain-path:
    description: "Path to the created keychain"
    value: ${{ steps.create-keychain.outputs.keychain-path }}
  system-user-keychain:
    description: "The prior user keychain before this action was run"
    value: ${{ steps.previous-values.outputs.system_user_keychain }}
  system-default-keychain:
    description: "The prior default keychain before this action was run"
    value: ${{ steps.previous-values.outputs.system_default_keychain }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: previous-values
      if: ${{ runner.os == 'macOS' }}
      run: |
        USER_KEYCHAIN=$(security list-keychain -d user | tr -d '"' | sed 's/^ *//')
        DEFAULT_KEYCHAIN=$(security default-keychain | tr -d '"' | sed 's/^ *//')
        echo "system_user_keychain=$USER_KEYCHAIN"
        echo "system_default_keychain=$DEFAULT_KEYCHAIN"
        echo "system_user_keychain=$USER_KEYCHAIN" >> "$GITHUB_OUTPUT"
        echo "system_default_keychain=$DEFAULT_KEYCHAIN" >> "$GITHUB_OUTPUT"

    - shell: bash
      id: create-keychain
      if: ${{ runner.os == 'macOS' }}
      run: |
        PASSWORD=${{ inputs.keychain-password }}
        if [ -z "$PASSWORD" ]; then
          PASSWORD=$(openssl rand -base64 12)
        fi
        KEYCHAIN_PATH=$RUNNER_TEMP/${{ inputs.keychain-name }}
        security create-keychain -p $PASSWORD $KEYCHAIN_PATH
        chmod 600 $KEYCHAIN_PATH
        security unlock-keychain -p $PASSWORD $KEYCHAIN_PATH
        echo "${{ inputs.certificate-p12-base64 }}" | base64 --decode > $RUNNER_TEMP/certificate.p12
        security import $RUNNER_TEMP/certificate.p12 -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        rm -f $RUNNER_TEMP/certificate.p12
        echo "keychain-path=$KEYCHAIN_PATH" >> "$GITHUB_OUTPUT"

        security list-keychains -d user -s $KEYCHAIN_PATH # Add the new keychain to the search path
        security default-keychain -s $KEYCHAIN_PATH
