name: go-test-lint

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        go-version: ${{ inputs.go-versions }}
        os: ${{ inputs.os-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: |
          go test --race --covermode=atomic ./...

  lint:
    runs-on: ${{ inputs.os-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...