name: go-test

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        go-version: ${{ inputs.go-versions }}
        os: ${{ inputs.os-versions }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: |
          go test --race --covermode=atomic ./...
