name: apple signing and provisioning support
description: create a file base keychain and use it to install apple signing certificate and also install a provisioning profile
inputs:
  provisioning-profile-base64:
    description: "Base64 encoded provisioning profile"
    required: false
  provisioning-profile-location:
    description: "Path to install the provisioning profile"
    required: false
    default: "provisioning.profile"
  certificate-p12-base64:
    description: "Base64 encoded P12 certificate"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.provisioning-profile-base64 != '' && inputs.provisioning-profile-location != '' }}
      run: |
        if [[ "${{ inputs.provisioning-profile-location }}" == *..* ]]; then
          echo "Error: Path traversal detected in provisioning-profile-location." >&2
          exit 1
        fi
        echo -n ${{ inputs.provisioning-profile-base64 }} | base64 --decode -o $RUNNER_TEMP/${{ inputs.provisioning-profile-location }}
    - shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        set -x
        echo "${{ inputs.certificate-p12-base64 }}" | base64 --decode > $RUNNER_TEMP/certificate.p12
        PASSWORD=$(openssl rand -base64 12)
        KEYCHAIN_PATH=$RUNNER_TEMP/keychain-ci-testing.keychain-db
        security create-keychain -p $PASSWORD $KEYCHAIN_PATH
        security unlock-keychain -p $PASSWORD $KEYCHAIN_PATH
        security import $RUNNER_TEMP/certificate.p12 -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychains -d user -s $KEYCHAIN_PATH # Add the new keychain to the search path
