name: apple signing and provisioning support
description: install apple signing certificate and provisioning profile
inputs:
  provisioning-profile-location:
    description: whether and where to install the provisioning profile
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.provisioning-profile-location != "" }}
      run: |
        if [[ "${{ inputs.provisioning-profile-location }}" == *..* ]]; then
          echo "Error: Path traversal detected in provisioning-profile-location." >&2
          exit 1
        fi
        echo -n ${{ secrets.APPLE_PROVISIONING_PROFILE }} | base64 --decode -o $RUNNER_TEMP/$${inputs.provisioning-profile-location}
    - shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "${{ secrets.APPLE_SIGNING_CERTIFICATE }}" | base64 --decode > $RUNNER_TEMP/certificate.p12
        PASSWORD=$(openssl rand -base64 12)
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        security create-keychain -p $PASSWORD $KEYCHAIN_PATH
        security set-keychain-settings -t 3600 -u $KEYCHAIN_PATH
        security unlock-keychain -p $PASSWORD $KEYCHAIN_PATH
        security import $RUNNER_TEMP/certificate.p12 -P ${{ inputs.certificate-password }} -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        ls $RUNNER_TEMP
