name: apple signing support
description: create a file base keychain and use it to install apple signing certificate
inputs:
  certificate-p12-base64:
    description: "Base64 encoded P12 certificate"
    required: true
  keychain-name:
    description: "Name of the keychain to use"
    required: false
    default: "keychain-ci-testing.keychain-db"
runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        security import $RUNNER_TEMP/certificate.p12 -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
