name: pebble
description: "set up Pebble environment"
runs:
  using: "composite"
  steps:
    - name: install pebble and minica
      shell: bash
      run: |
        go install github.com/letsencrypt/pebble/v2/cmd/pebble@latest
        go install github.com/jsha/minica@latest

    - name: init pebble hosts Windows
      # Use PowerShell (the default shell on Windows runners)
      if: ${{ runner.os == 'Windows' && runner.environment != 'self-hosted' }}
      shell: pwsh
      run: |
        Add-Content -Path $env:WINDIR\System32\drivers\etc\hosts -Value "127.0.0.1 pebble.example.com pebble-test.example.com"
        Get-Content -Path $env:WINDIR\System32\drivers\etc\hosts

    - name: init pebble hosts Linux or macOS
      if: ${{ (runner.os == 'Linux' || runner.os == 'macOS') && runner.environment != 'self-hosted' }}
      shell: bash
      run: |
        if grep -q "pebble.example.com" /etc/hosts; then
          # can't use sudo on locally hosted runners, we must be
          # preconfigured with this entry
          echo "pebble.example.com already exists in /etc/hosts"
        else
          echo "127.0.0.1 pebble.example.com pebble-test.example.com" | sudo tee -a /etc/hosts
          cat /etc/hosts
        fi

    - name: test pebble hosts on Linux or macOS
      shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
        ping -c 2 pebble-test.example.com
        ping -c 2 pebble.example.com

    - name: test pebble hosts on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        ping -n 2 pebble-test.example.com
        ping -n 2 pebble.example.com
