name: go-lint

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: 'go versions to lint with'
        default: 1.25.x
      os-version: 
        type: string
        default: ubuntu-latest

permissions:
  contents: read

jobs:
  go-lint:
    runs-on: ${{ inputs.os-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
