name: go-lint-multimod

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: "go version to lint with"
        default: "stable"
      go-private:
        type: string
        default: ""
      runner:
        type: string
        default: |
          [
            "ubuntu-latest"
          ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      - uses: actions/checkout@v7
      - name: Normalize go-version
        id: goversion
        run: |
          v="${{ inputs.go-version }}"
          v="${v#>=}"
          echo "value=$v" >> "$GITHUB_OUTPUT"
      - uses: cloudengio/.github/.github/actions/go@main
        with:
          go-version: ${{ steps.goversion.outputs.value }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version: latest

      - name: Lint
        run: multimod --config=.multimod.yaml lint

      - name: Vulnerability
        run: multimod --config=.multimod.yaml govuln
