name: go-test

on:
  workflow_call:
    inputs:
      go-versions:
        required: true
        type: string  # Accepts the multi-line string
        description: 'Go versions to test, each on a new line with a "- " prefix'
      os-version: 
        required: true
        type: string
        default: ubuntu-latest

jobs:
  test:
    strategy:
      matrix:
        go-version: ${{ inputs.go-versions }}
    runs-on: ${{ inputs.os-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: |
          go test --race --covermode=atomic ./...
