name: go-test

on:
  workflow_call:
    inputs:
      go-versions:
        required: true
        type: string  
        description: 'Possibly multiple versions to test, as a json multi-line string ["1.15", "1.16"]'
        default: |
          [
            "1.22.x", 
            "1.23.x"
          ]
      os-version: 
        required: true
        type: string
        default: ubuntu-latest

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ${{ fromJson(inputs.go-versions) }}

    runs-on: ${{ inputs.os-version }}

    steps:
      - name: Set git to use LF
        if: ${{ inputs.os-version == 'windows-latest' }} 
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: |
          go test --race --covermode=atomic ./...
